In [1]:
import numpy as np
import scipy.stats as stats
from multiprocessing import Pool
from functools import partial
from pathlib import Path
from lmmcomparison import poweranalysis

seedlist = np.loadtxt("seedlist.csv", dtype='int', delimiter=',')

In [2]:
hierarchy = [2,3,3]

bootstraps = 100
permutations = 100
treatment_col = 0
compare = "corr"

loop_count = 729

worker = partial(
poweranalysis,
compare=compare,
loops=loop_count,
treatment_col=treatment_col,
bootstraps = bootstraps,
permutations = permutations)

In [11]:
%%time


num_level_1s = [3, 6, 9, 12, 15, 18, 21]
seed = tuple(idx + 336 for idx, v in enumerate(num_level_1s))
final = np.empty((len(num_level_1s), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    paramlist = [[0, 0], [stats.norm], [stats.norm]]
    paramlist = [paramlist] * num_processors
    

    with Pool(processes = num_processors) as p:

        for idx, v in enumerate(num_level_1s):

            hierarchy = [2, v, 3]
            containers = [hierarchy] * num_processors

            ss = np.random.SeedSequence(seedlist[seed[idx]])
            child_seeds = ss.spawn(num_processors)
            seeds = [np.random.default_rng(s) for s in child_seeds]

            output = p.starmap(worker, zip(containers, paramlist, seeds))

            final[idx, 0] = v    
            final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
            print(final[idx])
    
    
    filename = "norm_hierarch_vs_lmm.csv"
    np.savetxt(Path("figures") / "simulations" / filename, final, delimiter=',') 


[3.         0.05408583 0.28052126]
[6.         0.05330198 0.25034294]
[9.         0.04644327 0.2260435 ]
[12.          0.04889281  0.22545561]
[15.          0.05114638  0.22574956]
[18.          0.05036253  0.223398  ]
[21.          0.05330198  0.22623947]
CPU times: total: 46.9 ms
Wall time: 15min 37s


In [3]:
%%time


num_level_1s = [3, 6, 9, 12, 15, 18, 21]
seed = tuple(idx + 346 for idx, v in enumerate(num_level_1s))
final = np.empty((len(num_level_1s), 3))

  

if __name__ ==  '__main__': 
    num_processors = 10

    paramlist = [[0, 0], [stats.lognorm, 1], [stats.lognorm, 1]]
    paramlist = [paramlist] * num_processors
    

    with Pool(processes = num_processors) as p:

        for idx, v in enumerate(num_level_1s):

            hierarchy = [2, v, 3]
            containers = [hierarchy] * num_processors

            ss = np.random.SeedSequence(seedlist[seed[idx]])
            child_seeds = ss.spawn(num_processors)
            seeds = [np.random.default_rng(s) for s in child_seeds]

            output = p.starmap(worker, zip(containers, paramlist, seeds))

            final[idx, 0] = v    
            final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
            print(final[idx])

    filename = "lognorm_hierarch_vs_lmm.csv"
    np.savetxt(Path("figures") / "simulations" / filename, final, delimiter=',') 


[3.         0.05034294 0.27119342]
[6.         0.05089163 0.24320988]
[9.         0.04814815 0.22716049]
[12.          0.04855967  0.22414266]
[15.          0.04924554  0.22524005]
[18.          0.04540466  0.21947874]
[21.          0.05459534  0.22688615]
CPU times: total: 109 ms
Wall time: 14min 37s


In [4]:
%%time


num_level_1s = [3, 6, 9, 12, 15, 18, 21]
seed = tuple(idx + 356 for idx, v in enumerate(num_level_1s))
final = np.empty((len(num_level_1s), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    paramlist = [[0, 0], [stats.pareto, 2.839], [stats.pareto, 2.839]]
    paramlist = [paramlist] * num_processors
    

    with Pool(processes = num_processors) as p:

        for idx, v in enumerate(num_level_1s):

            hierarchy = [2, v, 3]
            containers = [hierarchy] * num_processors

            ss = np.random.SeedSequence(seedlist[seed[idx]])
            child_seeds = ss.spawn(num_processors)
            seeds = [np.random.default_rng(s) for s in child_seeds]

            output = p.starmap(worker, zip(containers, paramlist, seeds))

            final[idx, 0] = v    
            final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
            print(final[idx])

    filename = "pareto_hierarch_vs_lmm.csv"
    np.savetxt(Path("figures") / "simulations" / filename, final, delimiter=',') 

[3.         0.04771703 0.27140898]
[6.         0.05036253 0.23809524]
[9.         0.04957868 0.23476386]
[12.          0.05153831  0.22525965]
[15.          0.05379189  0.22947286]
[18.          0.04722712  0.22378993]
[21.          0.05036253  0.22114442]
CPU times: total: 141 ms
Wall time: 16min 58s


In [5]:
%%time


num_level_1s = [3, 6, 9, 12, 15, 18, 21]
seed = tuple(idx + 366 for idx, v in enumerate(num_level_1s))
final = np.empty((len(num_level_1s), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    paramlist = [[0, 0], [stats.gamma, 2], [stats.gamma, 2]]
    paramlist = [paramlist] * num_processors
    

    with Pool(processes = num_processors) as p:

        for idx, v in enumerate(num_level_1s):

            hierarchy = [2, v, 3]
            containers = [hierarchy] * num_processors

            ss = np.random.SeedSequence(seedlist[seed[idx]])
            child_seeds = ss.spawn(num_processors)
            seeds = [np.random.default_rng(s) for s in child_seeds]

            output = p.starmap(worker, zip(containers, paramlist, seeds))

            final[idx, 0] = v    
            final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
            print(final[idx])

    filename = "gamma_hierarch_vs_lmm.csv"
    np.savetxt(Path("figures") / "simulations" / filename, final, delimiter=',') 


[3.         0.0494807  0.27219283]
[6.         0.04869684 0.23780129]
[9.         0.05006859 0.22957084]
[12.          0.04908877  0.22908093]
[15.          0.05281207  0.22378993]
[18.          0.04918675  0.22124241]
[21.          0.05281207  0.22349598]
CPU times: total: 109 ms
Wall time: 15min 39s
