In [1]:
import pandas as pd
import numpy as np
import numba as nb
import scipy.stats as stats
import hierarch as ha
from multiprocessing import Pool
from functools import partial
import os
from poweranalysis import conf_int_analysis

seedlist = np.loadtxt("seedlist.csv", dtype='int', delimiter=',')

In [2]:
folder = "E:\OneDrive\FluorescenceImagingPython\\confidence intervals_t"

In [3]:
hierarchy = [2,3,3]

bootstraps = 250
permutations = 'all'
interval = 95
treatment_col = 0
compare = "means"

loop_count = 729

worker = partial(
conf_int_analysis,
interval=interval,
compare=compare,
loops=loop_count,
treatment_col=treatment_col,
bootstraps = bootstraps,
permutations = permutations,
iterations = 10,
tolerance = 0.5
)

In [4]:
distributions = "lognorm_lognorm_"

In [5]:
%%time


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(668, 675))
final = np.empty((len(mean_diff), 4))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, v*np.sqrt(stats.lognorm.var(1)*2)]
        true_slope = [treat[1]] * num_processors

        paramlist = [treat, [stats.lognorm, 1], [stats.lognorm, 1]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()



[0.         0.95169508 0.9739369  0.96159122]
[1.52819735 0.95169508 0.97423084 0.95972957]
[3.0563947  0.95100921 0.97521066 0.96041544]
[4.58459204 0.95169508 0.97462277 0.96061141]
[6.11278939 0.95443857 0.97403488 0.96139526]
[7.64098674 0.95130316 0.97472075 0.96051342]
[9.16918409 0.95394866 0.97550461 0.96257104]
Wall time: 7min 31s


In [6]:
print(final)


[[0.         0.95169508 0.9739369  0.96159122]
 [1.52819735 0.95169508 0.97423084 0.95972957]
 [3.0563947  0.95100921 0.97521066 0.96041544]
 [4.58459204 0.95169508 0.97462277 0.96061141]
 [6.11278939 0.95443857 0.97403488 0.96139526]
 [7.64098674 0.95130316 0.97472075 0.96051342]
 [9.16918409 0.95394866 0.97550461 0.96257104]]


In [7]:
distributions = "norm_norm_"

In [8]:
%%time

mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(675, 682))
final = np.empty((len(mean_diff), 4))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, v*np.sqrt(stats.norm.var(1)*2)]
        true_slope = [treat[1]] * num_processors

        paramlist = [treat, [stats.norm, 1], [stats.norm, 1]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.95081325 0.96619636 0.95257692]
[0.70710678 0.94855967 0.96511856 0.94983343]
[1.41421356 0.95149912 0.96668626 0.95189104]
[2.12132034 0.94473839 0.96129728 0.94591417]
[2.82842712 0.95100921 0.96668626 0.95277288]
[3.53553391 0.94767784 0.962767   0.94826573]
[4.24264069 0.94473839 0.96198315 0.94552224]
Wall time: 7min 10s


In [9]:
print(final)


[[0.         0.95081325 0.96619636 0.95257692]
 [0.70710678 0.94855967 0.96511856 0.94983343]
 [1.41421356 0.95149912 0.96668626 0.95189104]
 [2.12132034 0.94473839 0.96129728 0.94591417]
 [2.82842712 0.95100921 0.96668626 0.95277288]
 [3.53553391 0.94767784 0.962767   0.94826573]
 [4.24264069 0.94473839 0.96198315 0.94552224]]


In [10]:
distributions = "pareto_pareto_"

In [11]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(682, 689))
final = np.empty((len(mean_diff), 4))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, v*np.sqrt(stats.pareto.var(2.839)*2)]
        true_slope = [treat[1]] * num_processors

        paramlist = [treat, [stats.pareto, 2.839], [stats.pareto, 2.839]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.95238095 0.97609249 0.95992553]
[0.70730217 0.95306682 0.97619048 0.96139526]
[1.41460433 0.95012738 0.97550461 0.9616892 ]
[2.1219065  0.95571233 0.9776602  0.96462865]
[2.82920867 0.9494415  0.97413286 0.95874976]
[3.53651084 0.95287086 0.97648442 0.96257104]
[4.243813   0.95198903 0.97599451 0.96188517]
Wall time: 7min 46s


In [12]:
print(final)


[[0.         0.95238095 0.97609249 0.95992553]
 [0.70730217 0.95306682 0.97619048 0.96139526]
 [1.41460433 0.95012738 0.97550461 0.9616892 ]
 [2.1219065  0.95571233 0.9776602  0.96462865]
 [2.82920867 0.9494415  0.97413286 0.95874976]
 [3.53651084 0.95287086 0.97648442 0.96257104]
 [4.243813   0.95198903 0.97599451 0.96188517]]


In [13]:
distributions = "gamma_gamma_"

In [14]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(689, 696))
final = np.empty((len(mean_diff), 4))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, v*np.sqrt(stats.gamma.var(2)*2)]
        true_slope = [treat[1]] * num_processors

        paramlist = [treat, [stats.gamma, 2], [stats.gamma, 2]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.94865765 0.96737213 0.95189104]
[1.         0.95012738 0.96874388 0.95247893]
[2.         0.94767784 0.96560847 0.95002939]
[3.         0.95100921 0.96844993 0.95238095]
[4.         0.95169508 0.97001764 0.95404664]
[5.         0.95483049 0.96844993 0.95483049]
[6.         0.94757985 0.96609837 0.94865765]
Wall time: 7min 11s


In [15]:
print(final)


[[0.         0.94865765 0.96737213 0.95189104]
 [1.         0.95012738 0.96874388 0.95247893]
 [2.         0.94767784 0.96560847 0.95002939]
 [3.         0.95100921 0.96844993 0.95238095]
 [4.         0.95169508 0.97001764 0.95404664]
 [5.         0.95483049 0.96844993 0.95483049]
 [6.         0.94757985 0.96609837 0.94865765]]


In [16]:
hierarchy = [2, 4, 3]
bootstraps = 100
permutations = 'all'

interval = 95
treatment_col = 0
compare = "means"

loop_count = 729

worker = partial(
conf_int_analysis,
interval=interval,
compare=compare,
loops=loop_count,
treatment_col=treatment_col,
bootstraps = bootstraps,
permutations = permutations,
iterations = 10,
tolerance = 0.5
)

In [17]:
distributions = "lognorm_lognorm_"

In [18]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(689, 696))
final = np.empty((len(mean_diff), 4))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, v*np.sqrt(stats.lognorm.var(1)*2)]
        true_slope = [treat[1]] * num_processors

        paramlist = [treat, [stats.lognorm, 1], [stats.lognorm, 1]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.95012738 0.97462277 0.96286498]
[1.52819735 0.95365471 0.9739369  0.96345287]
[3.0563947  0.95100921 0.97423084 0.96335489]
[4.58459204 0.95022536 0.97472075 0.96149324]
[6.11278939 0.95189104 0.97628846 0.96472663]
[7.64098674 0.95247893 0.97491672 0.96129728]
[9.16918409 0.95238095 0.97276112 0.96198315]
Wall time: 8min 37s


In [19]:
print(final)


[[0.         0.95012738 0.97462277 0.96286498]
 [1.52819735 0.95365471 0.9739369  0.96345287]
 [3.0563947  0.95100921 0.97423084 0.96335489]
 [4.58459204 0.95022536 0.97472075 0.96149324]
 [6.11278939 0.95189104 0.97628846 0.96472663]
 [7.64098674 0.95247893 0.97491672 0.96129728]
 [9.16918409 0.95238095 0.97276112 0.96198315]]


In [20]:
distributions = "norm_norm_"

In [21]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(696, 703))
final = np.empty((len(mean_diff), 4))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, v*np.sqrt(stats.norm.var(1)*2)]
        true_slope = [treat[1]] * num_processors

        paramlist = [treat, [stats.norm, 1], [stats.norm, 1]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.95042132 0.95767196 0.9494415 ]
[0.70710678 0.94757985 0.95502646 0.94660004]
[1.41421356 0.95110719 0.95963159 0.95100921]
[2.12132034 0.94797178 0.95698609 0.94983343]
[2.82842712 0.95179306 0.96002352 0.95061728]
[3.53553391 0.95287086 0.9601215  0.95208701]
[4.24264069 0.95198903 0.96198315 0.95208701]
Wall time: 7min 39s


In [22]:
print(final)


[[0.         0.95042132 0.95767196 0.9494415 ]
 [0.70710678 0.94757985 0.95502646 0.94660004]
 [1.41421356 0.95110719 0.95963159 0.95100921]
 [2.12132034 0.94797178 0.95698609 0.94983343]
 [2.82842712 0.95179306 0.96002352 0.95061728]
 [3.53553391 0.95287086 0.9601215  0.95208701]
 [4.24264069 0.95198903 0.96198315 0.95208701]]


In [23]:
distributions = "pareto_pareto_"

In [24]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(703, 710))
final = np.empty((len(mean_diff), 4))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, v*np.sqrt(stats.pareto.var(2.839)*2)]
        true_slope = [treat[1]] * num_processors

        paramlist = [treat, [stats.pareto, 2.839], [stats.pareto, 2.839]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.95149912 0.97511268 0.96247306]
[0.70730217 0.94973545 0.97609249 0.96188517]
[1.41460433 0.9542426  0.97599451 0.96639232]
[2.1219065  0.95032334 0.97540662 0.9638448 ]
[2.82920867 0.95512444 0.97579855 0.96521654]
[3.53651084 0.95149912 0.97579855 0.96355085]
[4.243813   0.95355673 0.97589653 0.96423672]
Wall time: 8min 52s


In [25]:
print(final)

[[0.         0.95149912 0.97511268 0.96247306]
 [0.70730217 0.94973545 0.97609249 0.96188517]
 [1.41460433 0.9542426  0.97599451 0.96639232]
 [2.1219065  0.95032334 0.97540662 0.9638448 ]
 [2.82920867 0.95512444 0.97579855 0.96521654]
 [3.53651084 0.95149912 0.97579855 0.96355085]
 [4.243813   0.95355673 0.97589653 0.96423672]]


In [26]:
distributions = "gamma_gamma_"

In [27]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(710, 717))
final = np.empty((len(mean_diff), 4))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, v*np.sqrt(stats.gamma.var(2)*2)]
        true_slope = [treat[1]] * num_processors

        paramlist = [treat, [stats.gamma, 2], [stats.gamma, 2]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.95365471 0.96600039 0.95483049]
[1.         0.9505193  0.96178718 0.95169508]
[2.         0.94885362 0.9616892  0.95071527]
[3.         0.95091123 0.96551048 0.95365471]
[4.         0.94953949 0.962767   0.95326279]
[5.         0.9494415  0.96315893 0.95228297]
[6.         0.94963747 0.962767   0.95228297]
Wall time: 7min 55s


In [28]:
print(final)

[[0.         0.95365471 0.96600039 0.95483049]
 [1.         0.9505193  0.96178718 0.95169508]
 [2.         0.94885362 0.9616892  0.95071527]
 [3.         0.95091123 0.96551048 0.95365471]
 [4.         0.94953949 0.962767   0.95326279]
 [5.         0.9494415  0.96315893 0.95228297]
 [6.         0.94963747 0.962767   0.95228297]]


In [29]:
hierarchy = [3, 2, 4, 3]

bootstraps = 100
permutations = 100
interval = 95
treatment_col = 1
compare = "means"

loop_count = 729

worker = partial(
conf_int_analysis,
interval=interval,
compare=compare,
loops=loop_count,
treatment_col=treatment_col,
bootstraps = bootstraps,
permutations = permutations,
iterations = 10,
tolerance = 0.5
)

In [30]:
distributions = "lognorm_lognorm_"

In [31]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(717, 724))
final = np.empty((len(mean_diff), 4))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14
    
    containers = [hierarchy] * num_processors


    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, v*np.sqrt(stats.lognorm.var(1)*2)] * 3
        true_slope = [treat[1]] * num_processors

        paramlist = [[stats.lognorm, 1], treat, [stats.lognorm, 1], [stats.lognorm, 1]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])


    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.9542426  0.97893396 0.97677837]
[1.52819735 0.95277288 0.97844405 0.97677837]
[3.0563947  0.95483049 0.97971781 0.97756222]
[4.58459204 0.95012738 0.97775818 0.97521066]
[6.11278939 0.95189104 0.97815011 0.97570057]
[7.64098674 0.95179306 0.97932589 0.97717029]
[9.16918409 0.95149912 0.97687635 0.97432883]
Wall time: 9min 18s


In [32]:
print(final)

[[0.         0.9542426  0.97893396 0.97677837]
 [1.52819735 0.95277288 0.97844405 0.97677837]
 [3.0563947  0.95483049 0.97971781 0.97756222]
 [4.58459204 0.95012738 0.97775818 0.97521066]
 [6.11278939 0.95189104 0.97815011 0.97570057]
 [7.64098674 0.95179306 0.97932589 0.97717029]
 [9.16918409 0.95149912 0.97687635 0.97432883]]


In [33]:
distributions = "norm_norm_"

In [34]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(724, 731))
final = np.empty((len(mean_diff), 4))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, v*np.sqrt(stats.norm.var()*2)] * 3
        true_slope = [treat[1]] * num_processors

        paramlist = [[stats.norm], treat, [stats.norm], [stats.norm]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.95345875 0.97824809 0.97775818]
[0.70710678 0.95081325 0.97677837 0.97628846]
[1.41421356 0.94963747 0.97462277 0.97403488]
[2.12132034 0.9478738  0.97432883 0.97344699]
[2.82842712 0.95110719 0.97805213 0.97785616]
[3.53553391 0.95071527 0.97668038 0.97628846]
[4.24264069 0.95238095 0.97844405 0.97726827]
Wall time: 8min 49s


In [35]:
print(final)


[[0.         0.95345875 0.97824809 0.97775818]
 [0.70710678 0.95081325 0.97677837 0.97628846]
 [1.41421356 0.94963747 0.97462277 0.97403488]
 [2.12132034 0.9478738  0.97432883 0.97344699]
 [2.82842712 0.95110719 0.97805213 0.97785616]
 [3.53553391 0.95071527 0.97668038 0.97628846]
 [4.24264069 0.95238095 0.97844405 0.97726827]]


In [36]:
distributions = "pareto_pareto_"

In [37]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(731, 738))
final = np.empty((len(mean_diff), 4))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, v*np.sqrt(stats.pareto.var(2.839)*2)] * 3
        true_slope = [treat[1]] * num_processors

        paramlist = [[stats.pareto, 2.839], treat, [stats.pareto, 2.839], [stats.pareto, 2.839]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()



[0.         0.95140114 0.97912992 0.97687635]
[0.70730217 0.95463453 0.98040368 0.97775818]
[1.41460433 0.95541838 0.97971781 0.97707231]
[2.1219065  0.95208701 0.97677837 0.97374094]
[2.82920867 0.95130316 0.97864002 0.97599451]
[3.53651084 0.95336077 0.97893396 0.97550461]
[4.243813   0.95345875 0.97912992 0.97619048]
Wall time: 9min 24s


In [38]:
print(final)

[[0.         0.95140114 0.97912992 0.97687635]
 [0.70730217 0.95463453 0.98040368 0.97775818]
 [1.41460433 0.95541838 0.97971781 0.97707231]
 [2.1219065  0.95208701 0.97677837 0.97374094]
 [2.82920867 0.95130316 0.97864002 0.97599451]
 [3.53651084 0.95336077 0.97893396 0.97550461]
 [4.243813   0.95345875 0.97912992 0.97619048]]


In [39]:
distributions = "gamma_gamma_"

In [40]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(738, 745))
final = np.empty((len(mean_diff), 4))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, v*np.sqrt(stats.gamma.var(2)*2)] * 3
        true_slope = [treat[1]] * num_processors

        paramlist = [[stats.gamma, 2], treat, [stats.gamma, 2], [stats.gamma, 2]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])


    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()



[0.         0.9526749  0.97717029 0.97589653]
[1.         0.95287086 0.9776602  0.97697433]
[2.         0.9526749  0.97540662 0.97413286]
[3.         0.95140114 0.97619048 0.97491672]
[4.         0.95179306 0.97589653 0.97530864]
[5.         0.95247893 0.97609249 0.97481873]
[6.         0.95287086 0.97687635 0.97560259]
Wall time: 8min 44s


In [41]:
print(final)


[[0.         0.9526749  0.97717029 0.97589653]
 [1.         0.95287086 0.9776602  0.97697433]
 [2.         0.9526749  0.97540662 0.97413286]
 [3.         0.95140114 0.97619048 0.97491672]
 [4.         0.95179306 0.97589653 0.97530864]
 [5.         0.95247893 0.97609249 0.97481873]
 [6.         0.95287086 0.97687635 0.97560259]]


In [42]:
folder = os.path.abspath('confidence intervals corr')

In [43]:
hierarchy = [3,3,3]
bootstraps = 50
permutations = 200
interval = 95
treatment_col = 0
compare = "corr"

loop_count = 729

worker = partial(
conf_int_analysis,
interval=interval,
compare=compare,
loops=loop_count,
treatment_col=treatment_col,
bootstraps = bootstraps,
permutations = permutations,
iterations = 10,
tolerance = 0.2
)

In [44]:
distributions = "lognorm_lognorm_"

In [45]:
%%time


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(668, 675))
final = np.empty((len(mean_diff), 3))
3
import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, (v/2)*np.sqrt(stats.lognorm.var(1)*2), (v)*np.sqrt(stats.lognorm.var(1)*2)]
        true_slope = [treat[1]] * num_processors

        paramlist = [treat, [stats.lognorm, 1], [stats.lognorm, 1]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()



[0.         0.95091123 0.96257104]
[0.76409867 0.94826573 0.95845581]
[1.52819735 0.94738389 0.95894572]
[2.29229602 0.95012738 0.96002352]
[3.0563947  0.94963747 0.95914168]
[3.82049337 0.95022536 0.9601215 ]
[4.58459204 0.94973545 0.96002352]
Wall time: 12min 39s


In [46]:
distributions = "norm_norm_"

In [47]:
%%time

mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(675, 682))
final = np.empty((len(mean_diff), 3))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, (v/2)*np.sqrt(stats.norm.var(1)*2),v*np.sqrt(stats.norm.var(1)*2)]
        true_slope = [treat[1]] * num_processors

        paramlist = [treat, [stats.norm, 1], [stats.norm, 1]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.94552224 0.94689398]
[0.35355339 0.94777582 0.94973545]
[0.70710678 0.94601215 0.94767784]
[1.06066017 0.94493435 0.94963747]
[1.41421356 0.94983343 0.95238095]
[1.76776695 0.94748187 0.95022536]
[2.12132034 0.95042132 0.95042132]
Wall time: 12min 5s


In [48]:
print(final)


[[0.         0.94552224 0.94689398]
 [0.35355339 0.94777582 0.94973545]
 [0.70710678 0.94601215 0.94767784]
 [1.06066017 0.94493435 0.94963747]
 [1.41421356 0.94983343 0.95238095]
 [1.76776695 0.94748187 0.95022536]
 [2.12132034 0.95042132 0.95042132]]


In [49]:
distributions = "pareto_pareto_"

In [50]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(682, 689))
final = np.empty((len(mean_diff), 3))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, (v/2)*np.sqrt(stats.pareto.var(2.839)*2), v*np.sqrt(stats.pareto.var(2.839)*2)]
        true_slope = [treat[1]] * num_processors

        paramlist = [treat, [stats.pareto, 2.839], [stats.pareto, 2.839]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.94601215 0.95884774]
[0.35365108 0.95002939 0.96070939]
[0.70730217 0.94914756 0.95816187]
[1.06095325 0.9505193  0.96217911]
[1.41460433 0.95120517 0.96129728]
[1.76825542 0.94963747 0.96080737]
[2.1219065  0.95091123 0.96188517]
Wall time: 12min 50s


In [51]:
print(final)


[[0.         0.94601215 0.95884774]
 [0.35365108 0.95002939 0.96070939]
 [0.70730217 0.94914756 0.95816187]
 [1.06095325 0.9505193  0.96217911]
 [1.41460433 0.95120517 0.96129728]
 [1.76825542 0.94963747 0.96080737]
 [2.1219065  0.95091123 0.96188517]]


In [52]:
distributions = "gamma_gamma_"

In [53]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(689, 696))
final = np.empty((len(mean_diff), 3))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, (v/2)*np.sqrt(stats.gamma.var(2)*2), v*np.sqrt(stats.gamma.var(2)*2)]
        true_slope = [treat[1]] * num_processors

        paramlist = [treat, [stats.gamma, 2], [stats.gamma, 2]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.95032334 0.95296884]
[0.5        0.95081325 0.95394866]
[1.         0.94806976 0.95277288]
[1.5        0.94336665 0.95032334]
[2.         0.95012738 0.95463453]
[2.5        0.95100921 0.95453655]
[3.         0.94846169 0.95414462]
Wall time: 12min 13s


In [54]:
print(final)


[[0.         0.95032334 0.95296884]
 [0.5        0.95081325 0.95394866]
 [1.         0.94806976 0.95277288]
 [1.5        0.94336665 0.95032334]
 [2.         0.95012738 0.95463453]
 [2.5        0.95100921 0.95453655]
 [3.         0.94846169 0.95414462]]


In [55]:
hierarchy = [4,3,3]
bootstraps = 50
permutations = 200

interval = 95
treatment_col = 0
compare = "corr"

loop_count = 729

worker = partial(
conf_int_analysis,
interval=interval,
compare=compare,
loops=loop_count,
treatment_col=treatment_col,
bootstraps = bootstraps,
permutations = permutations,
iterations = 10,
tolerance = 0.2
)

In [56]:
distributions = "lognorm_lognorm_"

In [57]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(689, 696))
final = np.empty((len(mean_diff), 3))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, (v/3)*np.sqrt(stats.lognorm.var(1)*2), (2*v/3)*np.sqrt(stats.lognorm.var(1)*2), v*np.sqrt(stats.lognorm.var(1)*2)]
        true_slope = [treat[1]] * num_processors

        paramlist = [treat, [stats.lognorm, 1], [stats.lognorm, 1]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.94993141 0.95953361]
[0.50939912 0.94865765 0.95865177]
[1.01879823 0.946796   0.95649618]
[1.52819735 0.94924554 0.9579659 ]
[2.03759646 0.95355673 0.95767196]
[2.54699558 0.95002939 0.9590437 ]
[3.0563947  0.95120517 0.96031746]
Wall time: 12min 4s


In [58]:
print(final)


[[0.         0.94993141 0.95953361]
 [0.50939912 0.94865765 0.95865177]
 [1.01879823 0.946796   0.95649618]
 [1.52819735 0.94924554 0.9579659 ]
 [2.03759646 0.95355673 0.95767196]
 [2.54699558 0.95002939 0.9590437 ]
 [3.0563947  0.95120517 0.96031746]]


In [59]:
distributions = "norm_norm_"

In [60]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(696, 703))
final = np.empty((len(mean_diff), 3))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0,(v/3)*np.sqrt(stats.norm.var(1)*2), (2*v/3)*np.sqrt(stats.norm.var(1)*2), v*np.sqrt(stats.norm.var(1)*2)]
        true_slope = [treat[1]] * num_processors

        paramlist = [treat, [stats.norm, 1], [stats.norm, 1]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.94708995 0.94620811]
[0.23570226 0.94993141 0.9526749 ]
[0.47140452 0.94924554 0.9526749 ]
[0.70710678 0.94836371 0.95091123]
[0.94280904 0.94914756 0.95277288]
[1.1785113  0.94846169 0.94953949]
[1.41421356 0.94738389 0.94699197]
Wall time: 11min 28s


In [61]:
print(final)


[[0.         0.94708995 0.94620811]
 [0.23570226 0.94993141 0.9526749 ]
 [0.47140452 0.94924554 0.9526749 ]
 [0.70710678 0.94836371 0.95091123]
 [0.94280904 0.94914756 0.95277288]
 [1.1785113  0.94846169 0.94953949]
 [1.41421356 0.94738389 0.94699197]]


In [62]:
distributions = "pareto_pareto_"

In [63]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(703, 710))
final = np.empty((len(mean_diff), 3))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, (v/3)*np.sqrt(stats.pareto.var(2.839)*2), (2*v/3)*np.sqrt(stats.pareto.var(2.839)*2), v*np.sqrt(stats.pareto.var(2.839)*2)]
        true_slope = [treat[1]] * num_processors

        paramlist = [treat, [stats.pareto, 2.839], [stats.pareto, 2.839]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.94973545 0.95776994]
[0.23576739 0.94826573 0.96041544]
[0.47153478 0.94464041 0.95600627]
[0.70730217 0.94846169 0.96100333]
[0.94306956 0.94806976 0.95600627]
[1.17883695 0.94934352 0.95767196]
[1.41460433 0.95032334 0.95972957]
Wall time: 12min 15s


In [64]:
print(final)

[[0.         0.94973545 0.95776994]
 [0.23576739 0.94826573 0.96041544]
 [0.47153478 0.94464041 0.95600627]
 [0.70730217 0.94846169 0.96100333]
 [0.94306956 0.94806976 0.95600627]
 [1.17883695 0.94934352 0.95767196]
 [1.41460433 0.95032334 0.95972957]]


In [65]:
distributions = "gamma_gamma_"

In [66]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(710, 717))
final = np.empty((len(mean_diff), 3))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, (v/3)*np.sqrt(stats.gamma.var(2)*2), (2*v/3)*np.sqrt(stats.gamma.var(2)*2), v*np.sqrt(stats.gamma.var(2)*2)]
        true_slope = [treat[1]] * num_processors

        paramlist = [treat, [stats.gamma, 2], [stats.gamma, 2]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.94797178 0.94865765]
[0.33333333 0.95169508 0.95277288]
[0.66666667 0.95149912 0.95365471]
[1.         0.95022536 0.95434058]
[1.33333333 0.94620811 0.95287086]
[1.66666667 0.94826573 0.95002939]
[2.         0.9489516  0.95238095]
Wall time: 11min 34s


In [67]:
print(final)

[[0.         0.94797178 0.94865765]
 [0.33333333 0.95169508 0.95277288]
 [0.66666667 0.95149912 0.95365471]
 [1.         0.95022536 0.95434058]
 [1.33333333 0.94620811 0.95287086]
 [1.66666667 0.94826573 0.95002939]
 [2.         0.9489516  0.95238095]]


In [68]:
hierarchy = [3, 4, 3, 3]

bootstraps = 100
permutations = 100

interval = 95
treatment_col = 1
compare = "corr"

loop_count = 729

worker = partial(
conf_int_analysis,
interval=interval,
compare=compare,
loops=loop_count,
treatment_col=treatment_col,
bootstraps = bootstraps,
permutations = permutations,
iterations = 10,
tolerance = 0.2
)

In [69]:
distributions = "lognorm_lognorm_"

In [70]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(717, 724))
final = np.empty((len(mean_diff), 3))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14
    
    containers = [hierarchy] * num_processors


    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, (v/3)*np.sqrt(stats.lognorm.var(1)*2), (2*v/3)*np.sqrt(stats.lognorm.var(1)*2), v*np.sqrt(stats.lognorm.var(1)*2)] * 3
        true_slope = [treat[1]] * num_processors

        paramlist = [[stats.lognorm, 1], treat, [stats.lognorm, 1], [stats.lognorm, 1]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])


    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.95277288 0.97001764]
[0.50939912 0.95247893 0.97315305]
[1.01879823 0.95708407 0.97217323]
[1.52819735 0.94924554 0.96923378]
[2.03759646 0.95110719 0.97031158]
[2.54699558 0.95179306 0.97099745]
[3.0563947  0.95306682 0.97158534]
Wall time: 12min 42s


In [71]:
print(final)

[[0.         0.95277288 0.97001764]
 [0.50939912 0.95247893 0.97315305]
 [1.01879823 0.95708407 0.97217323]
 [1.52819735 0.94924554 0.96923378]
 [2.03759646 0.95110719 0.97031158]
 [2.54699558 0.95179306 0.97099745]
 [3.0563947  0.95306682 0.97158534]]


In [72]:
distributions = "norm_norm_"

In [73]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(724, 731))
final = np.empty((len(mean_diff), 3))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0,(v/3)*np.sqrt(stats.norm.var(1)*2), (2*v/3)*np.sqrt(stats.norm.var(1)*2), v*np.sqrt(stats.norm.var(1)*2)] * 3
        true_slope = [treat[1]] * num_processors

        paramlist = [[stats.norm], treat, [stats.norm], [stats.norm]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.         0.95316481 0.97726827]
[0.23570226 0.95385068 0.97619048]
[0.47140452 0.95100921 0.97511268]
[0.70710678 0.95326279 0.97775818]
[0.94280904 0.95414462 0.97599451]
[1.1785113  0.95473251 0.97736626]
[1.41421356 0.95581031 0.97942387]
Wall time: 12min 24s


In [74]:
print(final)


[[0.         0.95316481 0.97726827]
 [0.23570226 0.95385068 0.97619048]
 [0.47140452 0.95100921 0.97511268]
 [0.70710678 0.95326279 0.97775818]
 [0.94280904 0.95414462 0.97599451]
 [1.1785113  0.95473251 0.97736626]
 [1.41421356 0.95581031 0.97942387]]


In [75]:
distributions = "pareto_pareto_"

In [76]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(731, 738))
final = np.empty((len(mean_diff), 3))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, (v/3)*np.sqrt(stats.pareto.var(2.839)*2), (2*v/3)*np.sqrt(stats.pareto.var(2.839)*2), v*np.sqrt(stats.pareto.var(2.839)*2)] * 3
        true_slope = [treat[1]] * num_processors

        paramlist = [[stats.pareto, 2.839], treat, [stats.pareto, 2.839], [stats.pareto, 2.839]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()



[0.         0.9505193  0.96923378]
[0.23576739 0.95238095 0.97217323]
[0.47153478 0.95198903 0.96982167]
[0.70730217 0.95394866 0.97138938]
[0.94306956 0.95032334 0.97236919]
[1.17883695 0.95110719 0.97236919]
[1.41460433 0.95198903 0.97227121]
Wall time: 12min 48s


In [77]:
print(final)

[[0.         0.9505193  0.96923378]
 [0.23576739 0.95238095 0.97217323]
 [0.47153478 0.95198903 0.96982167]
 [0.70730217 0.95394866 0.97138938]
 [0.94306956 0.95032334 0.97236919]
 [1.17883695 0.95110719 0.97236919]
 [1.41460433 0.95198903 0.97227121]]


In [78]:
distributions = "gamma_gamma_"

In [79]:
%%time

loop_count = 729


mean_diff = np.array([j for j in range(0,7)]) / 2
seed = tuple(i for i in range(738, 745))
final = np.empty((len(mean_diff), 3))

import poweranalysis

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(mean_diff):

        treat = [0, (v/3)*np.sqrt(stats.gamma.var(2)*2), (2*v/3)*np.sqrt(stats.gamma.var(2)*2), v*np.sqrt(stats.gamma.var(2)*2)] * 3
        true_slope = [treat[1]] * num_processors

        paramlist = [[stats.gamma, 2], treat, [stats.gamma, 2], [stats.gamma, 2]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, true_slope, seeds))

        final[idx, 0] = treat[1]    
        final[idx, 1:] = np.sum(output, axis=0) / (loop_count*num_processors)
        print(final[idx])


    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()



[0.         0.95277288 0.97334901]
[0.33333333 0.95071527 0.97383892]
[0.66666667 0.95365471 0.97315305]
[1.         0.95443857 0.97521066]
[1.33333333 0.95483049 0.97432883]
[1.66666667 0.95571233 0.97677837]
[2.         0.95306682 0.97442681]
Wall time: 12min 32s


In [80]:
print(final)


[[0.         0.95277288 0.97334901]
 [0.33333333 0.95071527 0.97383892]
 [0.66666667 0.95365471 0.97315305]
 [1.         0.95443857 0.97521066]
 [1.33333333 0.95483049 0.97432883]
 [1.66666667 0.95571233 0.97677837]
 [2.         0.95306682 0.97442681]]
