In [1]:
import pandas as pd
import numpy as np
import numba as nb
import scipy.stats as stats
import hierarch as ha
from multiprocessing import Pool
from functools import partial
import os
from poweranalysis import poweranalysis

seedlist = np.loadtxt("seedlist.csv", dtype='int', delimiter=',')

In [2]:
folder = os.path.abspath('size control corr many')

In [3]:
hierarchy = [3,3,3]

bootstraps = 50
permutations = 1000
treatment_col = 0
compare = "corr"

loop_count = 729

worker = partial(
poweranalysis,
compare=compare,
loops=loop_count,
treatment_col=treatment_col,
bootstraps = bootstraps,
permutations = permutations)

In [4]:
distributions = "lognorm_lognorm_"

In [5]:
%%time


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(336, 343))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):

        paramlist = [[0]*hierarchy[0], [stats.lognorm, 1, 0, 10**v], [stats.lognorm, 1]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v    
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()



[0.01       0.05300803 0.04076034]
[0.1        0.05349794 0.03978052]
[0.31622777 0.05095042 0.04428767]
[1.         0.04761905 0.03948658]
[3.16227766 0.04683519 0.03537135]
[10.          0.04673721  0.03213796]
[1.00000000e+02 4.92847345e-02 3.67430923e-02]
Wall time: 7min 36s


In [6]:
distributions = "norm_norm_"

In [7]:
%%time

interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(343, 350))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):

        paramlist = [[0]*hierarchy[0], [stats.norm, 0, 10**v], [stats.norm, 0, 1]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.05300803 0.0510484 ]
[0.1        0.05006859 0.05075446]
[0.31622777 0.05016657 0.04977464]
[1.         0.0494807  0.04791299]
[3.16227766 0.05036253 0.05193024]
[10.          0.05134235  0.05046051]
[1.00000000e+02 4.88928082e-02 4.81089555e-02]
Wall time: 7min 22s


In [8]:
print(final)


[[1.00000000e-02 5.30080345e-02 5.10484029e-02]
 [1.00000000e-01 5.00685871e-02 5.07544582e-02]
 [3.16227766e-01 5.01665687e-02 4.97746424e-02]
 [1.00000000e+00 4.94806976e-02 4.79129924e-02]
 [3.16227766e+00 5.03625318e-02 5.19302371e-02]
 [1.00000000e+01 5.13423476e-02 5.04605134e-02]
 [1.00000000e+02 4.88928082e-02 4.81089555e-02]]


In [9]:
distributions = "pareto_pareto_"

In [10]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(350, 357))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):

        paramlist = [[0]*hierarchy[0], [stats.pareto, 2.839, 0, 10**v], [stats.pareto, 2.839]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.05251813 0.04036841]
[0.1        0.05281207 0.04291593]
[0.31622777 0.05046051 0.04056437]
[1.         0.04997061 0.04134823]
[3.16227766 0.04497354 0.03586126]
[10.          0.05516363  0.0398785 ]
[1.00000000e+02 5.17342740e-02 3.45874976e-02]
Wall time: 7min 31s


In [11]:
print(final)


[[1.00000000e-02 5.25181266e-02 4.03684107e-02]
 [1.00000000e-01 5.28120713e-02 4.29159318e-02]
 [3.16227766e-01 5.04605134e-02 4.05643739e-02]
 [1.00000000e+00 4.99706055e-02 4.13482265e-02]
 [3.16227766e+00 4.49735450e-02 3.58612581e-02]
 [1.00000000e+01 5.51636292e-02 3.98785028e-02]
 [1.00000000e+02 5.17342740e-02 3.45874976e-02]]


In [12]:
distributions = "gamma_gamma_"

In [13]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(357, 364))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):

        paramlist = [[0]*hierarchy[0], [stats.gamma, 2, 0, 10**v], [stats.gamma, 2]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.05242015 0.04889281]
[0.1        0.05271409 0.04830492]
[0.31622777 0.05193024 0.05124437]
[1.         0.05046051 0.04683519]
[3.16227766 0.05271409 0.04781501]
[10.          0.04722712  0.04389575]
[1.00000000e+02 4.71291397e-02 4.42876739e-02]
Wall time: 7min 38s


In [14]:
print(final)


[[1.00000000e-02 5.24201450e-02 4.88928082e-02]
 [1.00000000e-01 5.27140898e-02 4.83049187e-02]
 [3.16227766e-01 5.19302371e-02 5.12443661e-02]
 [1.00000000e+00 5.04605134e-02 4.68351950e-02]
 [3.16227766e+00 5.27140898e-02 4.78150108e-02]
 [1.00000000e+01 4.72271213e-02 4.38957476e-02]
 [1.00000000e+02 4.71291397e-02 4.42876739e-02]]


In [15]:
hierarchy = [4, 3, 3]

bootstraps = 50
permutations = 1000
treatment_col = 0
compare = "corr"

loop_count = 729

worker = partial(
poweranalysis,
compare=compare,
loops=loop_count,
treatment_col=treatment_col,
bootstraps = bootstraps,
permutations = permutations)

In [16]:
distributions = "lognorm_lognorm_"

In [17]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(364, 371))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):

        paramlist = [[0]*hierarchy[0], [stats.lognorm, 1, 0, 10**v], [stats.lognorm, 1]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.05594748 0.04565942]
[0.1        0.05575152 0.04585538]
[0.31622777 0.053204   0.04330786]
[1.         0.05163629 0.04242602]
[3.16227766 0.04605134 0.04027043]
[10.          0.05300803  0.04017245]
[1.00000000e+02 4.85008818e-02 3.65471291e-02]
Wall time: 7min 53s


In [18]:
print(final)


[[1.00000000e-02 5.59474819e-02 4.56594160e-02]
 [1.00000000e-01 5.57515187e-02 4.58553792e-02]
 [3.16227766e-01 5.32039976e-02 4.33078581e-02]
 [1.00000000e+00 5.16362924e-02 4.24260239e-02]
 [3.16227766e+00 4.60513423e-02 4.02704292e-02]
 [1.00000000e+01 5.30080345e-02 4.01724476e-02]
 [1.00000000e+02 4.85008818e-02 3.65471291e-02]]


In [19]:
distributions = "norm_norm_"

In [20]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(371, 378))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):

        paramlist = [[0]*hierarchy[0], [stats.norm, 0, 10**v], [stats.norm, 0, 1]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.04899079 0.0521262 ]
[0.1        0.04859886 0.04585538]
[0.31622777 0.04997061 0.04928473]
[1.         0.04879483 0.04987262]
[3.16227766 0.0510484  0.04899079]
[10.          0.04967666  0.05036253]
[1.00000000e+02 4.96766608e-02 4.84029003e-02]
Wall time: 7min 49s


In [21]:
print(final)


[[1.00000000e-02 4.89907897e-02 5.21262003e-02]
 [1.00000000e-01 4.85988634e-02 4.58553792e-02]
 [3.16227766e-01 4.99706055e-02 4.92847345e-02]
 [1.00000000e+00 4.87948266e-02 4.98726239e-02]
 [3.16227766e+00 5.10484029e-02 4.89907897e-02]
 [1.00000000e+01 4.96766608e-02 5.03625318e-02]
 [1.00000000e+02 4.96766608e-02 4.84029003e-02]]


In [22]:
distributions = "pareto_pareto_"

In [23]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(378, 385))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):

        paramlist = [[0]*hierarchy[0], [stats.pareto, 2.839, 0, 10**v], [stats.pareto, 2.839]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.0473251  0.04213208]
[0.1        0.05026455 0.04144621]
[0.31622777 0.05085244 0.0436018 ]
[1.         0.0505585  0.04056437]
[3.16227766 0.04634529 0.03654713]
[10.          0.04859886  0.03997648]
[1.00000000e+02 4.65412502e-02 3.47834607e-02]
Wall time: 7min 32s


In [24]:
print(final)

[[1.00000000e-02 4.73251029e-02 4.21320792e-02]
 [1.00000000e-01 5.02645503e-02 4.14462081e-02]
 [3.16227766e-01 5.08524397e-02 4.36018029e-02]
 [1.00000000e+00 5.05584950e-02 4.05643739e-02]
 [3.16227766e+00 4.63452871e-02 3.65471291e-02]
 [1.00000000e+01 4.85988634e-02 3.99764844e-02]
 [1.00000000e+02 4.65412502e-02 3.47834607e-02]]


In [25]:
distributions = "gamma_gamma_"

In [26]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(385, 392))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):


        paramlist = [[0]*hierarchy[0], [stats.gamma, 2, 0, 10**v], [stats.gamma, 2]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.04859886 0.0457574 ]
[0.1        0.05006859 0.04820694]
[0.31622777 0.05193024 0.04899079]
[1.         0.05075446 0.05026455]
[3.16227766 0.04771703 0.04556143]
[10.          0.05085244  0.04673721]
[1.00000000e+02 4.84029003e-02 4.64432687e-02]
Wall time: 8min 25s


In [27]:
print(final)

[[1.00000000e-02 4.85988634e-02 4.57573976e-02]
 [1.00000000e-01 5.00685871e-02 4.82069371e-02]
 [3.16227766e-01 5.19302371e-02 4.89907897e-02]
 [1.00000000e+00 5.07544582e-02 5.02645503e-02]
 [3.16227766e+00 4.77170292e-02 4.55614345e-02]
 [1.00000000e+01 5.08524397e-02 4.67372134e-02]
 [1.00000000e+02 4.84029003e-02 4.64432687e-02]]


In [28]:
hierarchy = [3, 4, 3, 3]

bootstraps = 100
permutations = 1000
treatment_col = 1
compare = "corr"

loop_count = 729

worker = partial(
poweranalysis,
compare=compare,
loops=loop_count,
treatment_col=treatment_col,
bootstraps = bootstraps,
permutations = permutations)

In [29]:
distributions = "lognorm_lognorm_"

In [30]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(392, 399))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14
    
    containers = [hierarchy] * num_processors


    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):
         

        paramlist = [[stats.lognorm, 1, 0, 10**v], [0]*hierarchy[1]*3, [stats.lognorm, 1, 0, 10**v], [stats.lognorm, 1]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])


    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.05418381 0.04605134]
[0.1        0.05242015 0.04477758]
[0.31622777 0.04869684 0.03635117]
[1.         0.0484029  0.03047227]
[3.16227766 0.04536547 0.02429943]
[10.          0.05144033  0.02351558]
[1.00000000e+02 5.19302371e-02 2.42994317e-02]
Wall time: 18min 39s


In [31]:
print(final)

[[1.00000000e-02 5.41838134e-02 4.60513423e-02]
 [1.00000000e-01 5.24201450e-02 4.47775818e-02]
 [3.16227766e-01 4.86968450e-02 3.63511660e-02]
 [1.00000000e+00 4.84029003e-02 3.04722712e-02]
 [3.16227766e+00 4.53654713e-02 2.42994317e-02]
 [1.00000000e+01 5.14403292e-02 2.35155791e-02]
 [1.00000000e+02 5.19302371e-02 2.42994317e-02]]


In [32]:
distributions = "norm_norm_"

In [33]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(399, 406))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):
         

        paramlist = [[stats.norm, 0, 10**v], [0]*hierarchy[1]*3, [stats.norm, 0, 10**v], [stats.norm]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.04654125 0.04850088]
[0.1        0.04624731 0.04409171]
[0.31622777 0.04262199 0.03497942]
[1.         0.03742896 0.01851852]
[3.16227766 0.04771703 0.0223398 ]
[10.          0.05065648  0.02018421]
[1.00000000e+02 5.47717029e-02 2.08700764e-02]
Wall time: 18min 6s


In [34]:
print(final)


[[1.00000000e-02 4.65412502e-02 4.85008818e-02]
 [1.00000000e-01 4.62473055e-02 4.40917108e-02]
 [3.16227766e-01 4.26219871e-02 3.49794239e-02]
 [1.00000000e+00 3.74289634e-02 1.85185185e-02]
 [3.16227766e+00 4.77170292e-02 2.23398001e-02]
 [1.00000000e+01 5.06564766e-02 2.01842054e-02]
 [1.00000000e+02 5.47717029e-02 2.08700764e-02]]


In [35]:
distributions = "pareto_pareto_"

In [36]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(406, 413))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):

        paramlist = [[stats.pareto, 2.839, 0, 10**v], [0]*hierarchy[1]*3, [stats.pareto, 2.839, 0, 10**v], [stats.pareto, 2.839]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()



[0.01       0.05712326 0.04830492]
[0.1        0.04712914 0.0398785 ]
[0.31622777 0.04801097 0.03880071]
[1.         0.04507153 0.02821869]
[3.16227766 0.04957868 0.02361356]
[10.          0.04595336  0.02429943]
[1.00000000e+02 4.82069371e-02 2.16539291e-02]
Wall time: 22min 11s


In [37]:
print(final)

[[1.00000000e-02 5.71232608e-02 4.83049187e-02]
 [1.00000000e-01 4.71291397e-02 3.98785028e-02]
 [3.16227766e-01 4.80109739e-02 3.88007055e-02]
 [1.00000000e+00 4.50715266e-02 2.82186949e-02]
 [3.16227766e+00 4.95786792e-02 2.36135607e-02]
 [1.00000000e+01 4.59533608e-02 2.42994317e-02]
 [1.00000000e+02 4.82069371e-02 2.16539291e-02]]


In [38]:
distributions = "gamma_gamma_"

In [39]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(413, 420))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):

        paramlist = [[stats.gamma, 2, 0, 10**v], [0]*hierarchy[1]*3, [stats.gamma, 2, 0, 10**v], [stats.gamma, 2]]
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])


    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()



[0.01       0.05408583 0.05232216]
[0.1        0.04938272 0.04771703]
[0.31622777 0.04409171 0.03605722]
[1.         0.04487556 0.02547521]
[3.16227766 0.04791299 0.01910641]
[10.          0.05124437  0.02380952]
[1.00000000e+02 4.74230845e-02 2.16539291e-02]
Wall time: 17min 40s


In [40]:
print(final)


[[1.00000000e-02 5.40858319e-02 5.23221634e-02]
 [1.00000000e-01 4.93827160e-02 4.77170292e-02]
 [3.16227766e-01 4.40917108e-02 3.60572212e-02]
 [1.00000000e+00 4.48755634e-02 2.54752107e-02]
 [3.16227766e+00 4.79129924e-02 1.91064080e-02]
 [1.00000000e+01 5.12443661e-02 2.38095238e-02]
 [1.00000000e+02 4.74230845e-02 2.16539291e-02]]


In [41]:
folder = os.path.abspath('size control corr var')

In [42]:
hierarchy = [3,3,3]

bootstraps = 50
permutations = 1000
treatment_col = 0
compare = "corr"

loop_count = 729

worker = partial(
poweranalysis,
compare=compare,
loops=loop_count,
treatment_col=treatment_col,
bootstraps = bootstraps,
permutations = permutations)

In [43]:
distributions = "lognorm_lognorm_"

In [44]:
%%time


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(420, 427))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):
        t_1 = [stats.lognorm, 1, 0, (10**v)]

        loc_correction_2 = stats.lognorm.mean(1, 0, (10**v)) - stats.lognorm.mean(1, 0, 1.112*(10**v))

        t_2 = [stats.lognorm, 1, loc_correction_2, 1.112*(10**v)]

        loc_correction_3 = stats.lognorm.mean(1, 0, (10**v)) - stats.lognorm.mean(1, 0, 1.224*(10**v))

        t_3 = [stats.lognorm, 1, loc_correction_3, 1.224*(10**v)]

        paramlist = [[stats.norm, 0, 0],  [t_1]*hierarchy[1] + [t_2]*hierarchy[1] + [t_3]*hierarchy[1], [stats.lognorm, 1]]
        
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v    
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()



[0.01       0.05163629 0.04027043]
[0.1        0.05535959 0.04252401]
[0.31622777 0.05369391 0.04507153]
[1.         0.0494807  0.04262199]
[3.16227766 0.05193024 0.0420341 ]
[10.          0.05447776  0.03978052]
[1.00000000e+02 5.60454635e-02 4.04663923e-02]
Wall time: 7min 6s


In [45]:
distributions = "norm_norm_"

In [46]:
%%time

interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(427, 434))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):
        
        t_1 = [stats.norm, 0, 10**v]
        t_2 = [stats.norm, 0, 1.112*(10**v)]
        t_3 = [stats.norm, 0, 1.224*(10**v)]

        paramlist = [[stats.norm, 0, 0],  [t_1]*hierarchy[1] + [t_2]*hierarchy[1] + [t_3]*hierarchy[1], [stats.norm, 0, 1]]
        
        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.04997061 0.04987262]
[0.1        0.04683519 0.04556143]
[0.31622777 0.05085244 0.05144033]
[1.         0.05271409 0.05075446]
[3.16227766 0.05261611 0.0521262 ]
[10.          0.05046051  0.05173427]
[1.00000000e+02 4.90887713e-02 4.82069371e-02]
Wall time: 7min 8s


In [47]:
print(final)


[[1.00000000e-02 4.99706055e-02 4.98726239e-02]
 [1.00000000e-01 4.68351950e-02 4.55614345e-02]
 [3.16227766e-01 5.08524397e-02 5.14403292e-02]
 [1.00000000e+00 5.27140898e-02 5.07544582e-02]
 [3.16227766e+00 5.26161082e-02 5.21262003e-02]
 [1.00000000e+01 5.04605134e-02 5.17342740e-02]
 [1.00000000e+02 4.90887713e-02 4.82069371e-02]]


In [48]:
distributions = "pareto_pareto_"

In [49]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(434, 441))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):

        t_1 = [stats.pareto, 2.839, 0, 10**v]

        loc_correction_2 = stats.pareto.mean(2.839, 0, (10**v)) - stats.pareto.mean(2.839, 0, 1.112*(10**v))

        t_2 = [stats.pareto, 2.839, loc_correction_2, 1.112*(10**v)]

        loc_correction_3 = stats.pareto.mean(2.839, 0, (10**v)) - stats.pareto.mean(2.839, 0, 1.224*(10**v))

        t_3 = [stats.pareto, 2.839, loc_correction_3, 1.224*(10**v)]

        paramlist = [[stats.norm, 0, 0],  [t_1]*hierarchy[1] + [t_2]*hierarchy[1] + [t_3]*hierarchy[1], [stats.pareto, 2.839]]

        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.05016657 0.03791887]
[0.1        0.04830492 0.04085832]
[0.31622777 0.05202822 0.04232804]
[1.         0.05114638 0.03929061]
[3.16227766 0.05183226 0.03791887]
[10.          0.05388987  0.03929061]
[1.00000000e+02 5.68293161e-02 4.04663923e-02]
Wall time: 10min 53s


In [50]:
print(final)


[[1.00000000e-02 5.01665687e-02 3.79188713e-02]
 [1.00000000e-01 4.83049187e-02 4.08583186e-02]
 [3.16227766e-01 5.20282187e-02 4.23280423e-02]
 [1.00000000e+00 5.11463845e-02 3.92906134e-02]
 [3.16227766e+00 5.18322555e-02 3.79188713e-02]
 [1.00000000e+01 5.38898687e-02 3.92906134e-02]
 [1.00000000e+02 5.68293161e-02 4.04663923e-02]]


In [53]:
distributions = "gamma_gamma_"

In [54]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(441, 448))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):
        
        t_1 = [stats.gamma, 2, 0, (10**v)]

        loc_correction_2 = stats.gamma.mean(2, 0, (10**v)) - stats.gamma.mean(2, 0, 1.112*(10**v))

        t_2 = [stats.gamma, 2, loc_correction_2, 1.112*(10**v)]

        loc_correction_3 = stats.gamma.mean(2, 0, (10**v)) - stats.gamma.mean(2, 0, 1.224*(10**v))

        t_3 = [stats.gamma, 2, loc_correction_3, 1.224*(10**v)]

        paramlist = [[stats.norm, 0, 0],  [t_1]*hierarchy[1] + [t_2]*hierarchy[1] + [t_3]*hierarchy[1], [stats.gamma, 2]]

        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.05467372 0.05330198]
[0.1        0.05349794 0.04997061]
[0.31622777 0.04859886 0.04722712]
[1.         0.04850088 0.04791299]
[3.16227766 0.05144033 0.04899079]
[10.          0.04507153  0.04409171]
[1.00000000e+02 5.43797766e-02 4.96766608e-02]
Wall time: 6min 59s


In [55]:
print(final)


[[1.00000000e-02 5.46737213e-02 5.33019792e-02]
 [1.00000000e-01 5.34979424e-02 4.99706055e-02]
 [3.16227766e-01 4.85988634e-02 4.72271213e-02]
 [1.00000000e+00 4.85008818e-02 4.79129924e-02]
 [3.16227766e+00 5.14403292e-02 4.89907897e-02]
 [1.00000000e+01 4.50715266e-02 4.40917108e-02]
 [1.00000000e+02 5.43797766e-02 4.96766608e-02]]


In [56]:
hierarchy = [4, 3, 3]

bootstraps = 50
permutations = 1000
treatment_col = 0
compare = "corr"

loop_count = 729

worker = partial(
poweranalysis,
compare=compare,
loops=loop_count,
treatment_col=treatment_col,
bootstraps = bootstraps,
permutations = permutations)

In [57]:
distributions = "lognorm_lognorm_"

In [58]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(448, 455))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):

        t_1 = [stats.lognorm, 1, 0, (10 ** v)]

        loc_correction_2 = stats.lognorm.mean(1, 0, (10 ** v)) - stats.lognorm.mean(
            1, 0, 1.112 * (10 ** v)
        )

        t_2 = [stats.lognorm, 1, loc_correction_2, 1.112 * (10 ** v)]

        loc_correction_3 = stats.lognorm.mean(1, 0, (10 ** v)) - stats.lognorm.mean(
            1, 0, 1.224 * (10 ** v)
        )

        t_3 = [stats.lognorm, 1, loc_correction_3, 1.224 * (10 ** v)]

        loc_correction_4 = stats.lognorm.mean(1, 0, (10 ** v)) - stats.lognorm.mean(
            1, 0, 1.336 * (10 ** v)
        )

        t_4 = [stats.lognorm, 1, loc_correction_4, 1.336 * (10 ** v)]

        paramlist = [
            [stats.norm, 0, 0],
            [t_1] * hierarchy[1]
            + [t_2] * hierarchy[1]
            + [t_3] * hierarchy[1]
            + [t_4] * hierarchy[1],
            [stats.lognorm, 1],
        ]

        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.05359592 0.04252401]
[0.1        0.05251813 0.04242602]
[0.31622777 0.05065648 0.04223006]
[1.         0.04967666 0.04301391]
[3.16227766 0.05712326 0.04801097]
[10.          0.05339996  0.04252401]
[1.00000000e+02 5.68293161e-02 4.24260239e-02]
Wall time: 7min 9s


In [59]:
print(final)


[[1.00000000e-02 5.35959240e-02 4.25240055e-02]
 [1.00000000e-01 5.25181266e-02 4.24260239e-02]
 [3.16227766e-01 5.06564766e-02 4.22300607e-02]
 [1.00000000e+00 4.96766608e-02 4.30139134e-02]
 [3.16227766e+00 5.71232608e-02 4.80109739e-02]
 [1.00000000e+01 5.33999608e-02 4.25240055e-02]
 [1.00000000e+02 5.68293161e-02 4.24260239e-02]]


In [60]:
distributions = "norm_norm_"

In [61]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(455, 462))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):

        t_1 = [stats.norm, 0, 10**v]
        t_2 = [stats.norm, 0, 1.112*(10**v)]
        t_3 = [stats.norm, 0, 1.224*(10**v)]
        t_4 = [stats.norm, 0, 1.336*(10**v)]

        paramlist = [[stats.norm, 0, 0],  [t_1]*hierarchy[1] + [t_2]*hierarchy[1] + [t_3]*hierarchy[1] + [t_4]*hierarchy[1], [stats.norm, 0, 1]]

        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.04899079 0.04889281]
[0.1        0.05261611 0.05065648]
[0.31622777 0.05300803 0.04889281]
[1.         0.05006859 0.05016657]
[3.16227766 0.05251813 0.05183226]
[10.          0.04997061  0.04683519]
[1.00000000e+02 5.30080345e-02 5.27140898e-02]
Wall time: 7min 12s


In [62]:
print(final)


[[1.00000000e-02 4.89907897e-02 4.88928082e-02]
 [1.00000000e-01 5.26161082e-02 5.06564766e-02]
 [3.16227766e-01 5.30080345e-02 4.88928082e-02]
 [1.00000000e+00 5.00685871e-02 5.01665687e-02]
 [3.16227766e+00 5.25181266e-02 5.18322555e-02]
 [1.00000000e+01 4.99706055e-02 4.68351950e-02]
 [1.00000000e+02 5.30080345e-02 5.27140898e-02]]


In [63]:
distributions = "pareto_pareto_"

In [64]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(462, 469))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):

        t_1 = [stats.pareto, 2.839, 0, 10 ** v]

        loc_correction_2 = stats.pareto.mean(2.839, 0, (10 ** v)) - stats.pareto.mean(
            2.839, 0, 1.112 * (10 ** v)
        )

        t_2 = [stats.pareto, 2.839, loc_correction_2, 1.112 * (10 ** v)]

        loc_correction_3 = stats.pareto.mean(2.839, 0, (10 ** v)) - stats.pareto.mean(
            2.839, 0, 1.224 * (10 ** v)
        )

        t_3 = [stats.pareto, 2.839, loc_correction_3, 1.224 * (10 ** v)]

        loc_correction_4 = stats.pareto.mean(2.839, 0, (10 ** v)) - stats.pareto.mean(
            2.839, 0, 1.336 * (10 ** v)
        )

        t_4 = [stats.pareto, 2.839, loc_correction_4, 1.336 * (10 ** v)]

        paramlist = [
            [stats.norm, 0, 0],
            [t_1] * hierarchy[1]
            + [t_2] * hierarchy[1]
            + [t_3] * hierarchy[1]
            + [t_4] * hierarchy[1],
            [stats.pareto, 2.839],
        ]

        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.0521262  0.04125024]
[0.1        0.05251813 0.04252401]
[0.31622777 0.05163629 0.04448364]
[1.         0.05085244 0.04281795]
[3.16227766 0.05643739 0.0446796 ]
[10.          0.05947482  0.04330786]
[1.00000000e+02 6.16304135e-02 4.56594160e-02]
Wall time: 7min 10s


In [65]:
print(final)

[[1.00000000e-02 5.21262003e-02 4.12502450e-02]
 [1.00000000e-01 5.25181266e-02 4.25240055e-02]
 [3.16227766e-01 5.16362924e-02 4.44836371e-02]
 [1.00000000e+00 5.08524397e-02 4.28179502e-02]
 [3.16227766e+00 5.64373898e-02 4.46796002e-02]
 [1.00000000e+01 5.94748187e-02 4.33078581e-02]
 [1.00000000e+02 6.16304135e-02 4.56594160e-02]]


In [66]:
distributions = "gamma_gamma_"

In [67]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(469, 476))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):

        t_1 = [stats.gamma, 2, 0, (10 ** v)]

        loc_correction_2 = stats.gamma.mean(2, 0, (10 ** v)) - stats.gamma.mean(
            2, 0, 1.112 * (10 ** v)
        )

        t_2 = [stats.gamma, 2, loc_correction_2, 1.112 * (10 ** v)]

        loc_correction_3 = stats.gamma.mean(2, 0, (10 ** v)) - stats.gamma.mean(
            2, 0, 1.224 * (10 ** v)
        )

        t_3 = [stats.gamma, 2, loc_correction_3, 1.224 * (10 ** v)]

        loc_correction_4 = stats.gamma.mean(2, 0, (10 ** v)) - stats.gamma.mean(
            2, 0, 1.336 * (10 ** v)
        )

        t_4 = [stats.gamma, 2, loc_correction_4, 1.336 * (10 ** v)]

        paramlist = [
            [stats.norm, 0, 0],
            [t_1] * hierarchy[1]
            + [t_2] * hierarchy[1]
            + [t_3] * hierarchy[1]
            + [t_4] * hierarchy[1],
            [stats.gamma, 2],
        ]

        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.05193024 0.05046051]
[0.1        0.05398785 0.04997061]
[0.31622777 0.05516363 0.05183226]
[1.         0.04957868 0.05114638]
[3.16227766 0.05183226 0.04565942]
[10.          0.05016657  0.04859886]
[1.00000000e+02 5.37918871e-02 4.91867529e-02]
Wall time: 7min 39s


In [68]:
print(final)

[[1.00000000e-02 5.19302371e-02 5.04605134e-02]
 [1.00000000e-01 5.39878503e-02 4.99706055e-02]
 [3.16227766e-01 5.51636292e-02 5.18322555e-02]
 [1.00000000e+00 4.95786792e-02 5.11463845e-02]
 [3.16227766e+00 5.18322555e-02 4.56594160e-02]
 [1.00000000e+01 5.01665687e-02 4.85988634e-02]
 [1.00000000e+02 5.37918871e-02 4.91867529e-02]]


In [69]:
hierarchy = [3, 4, 3, 3]

bootstraps = 50
permutations = 2000
treatment_col = 1
compare = "corr"

loop_count = 729

worker = partial(
poweranalysis,
compare=compare,
loops=loop_count,
treatment_col=treatment_col,
bootstraps = bootstraps,
permutations = permutations)

In [70]:
distributions = "lognorm_lognorm_"

In [71]:

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(476, 483))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14
    
    containers = [hierarchy] * num_processors


    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):
         

        t_1 = [stats.lognorm, 1, 0, (10 ** v)]

        loc_correction_2 = stats.lognorm.mean(1, 0, (10 ** v)) - stats.lognorm.mean(
            1, 0, 1.112 * (10 ** v))

        t_2 = [stats.lognorm, 1, loc_correction_2, 1.112 * (10 ** v)]

        loc_correction_3 = stats.lognorm.mean(1, 0, (10 ** v)) - stats.lognorm.mean(
            1, 0, 1.224 * (10 ** v)
        )

        t_3 = [stats.lognorm, 1, loc_correction_3, 1.224 * (10 ** v)]

        loc_correction_4 = stats.lognorm.mean(1, 0, (10 ** v)) - stats.lognorm.mean(
            1, 0, 1.336 * (10 ** v)
        )

        t_4 = [stats.lognorm, 1, loc_correction_4, 1.336 * (10 ** v)]

        paramlist = [
            [stats.lognorm, 1, 0, (10 ** v)],
            [stats.norm, 0, 0],
            (
                [t_1] * hierarchy[2]
                + [t_2] * hierarchy[2]
                + [t_3] * hierarchy[2]
                + [t_4] * hierarchy[2]
            )
            * hierarchy[0],
            [stats.lognorm, 1],
        ]

        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])


    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.058495   0.04879483]
[0.1        0.053204   0.04389575]
[0.31622777 0.04928473 0.03948658]
[1.         0.04918675 0.02880658]
[3.16227766 0.05594748 0.03115814]
[10.          0.05908289  0.02919851]
[1.00000000e+02 5.84950029e-02 2.95904370e-02]


In [72]:
print(final)

[[1.00000000e-02 5.84950029e-02 4.87948266e-02]
 [1.00000000e-01 5.32039976e-02 4.38957476e-02]
 [3.16227766e-01 4.92847345e-02 3.94865765e-02]
 [1.00000000e+00 4.91867529e-02 2.88065844e-02]
 [3.16227766e+00 5.59474819e-02 3.11581423e-02]
 [1.00000000e+01 5.90828924e-02 2.91985107e-02]
 [1.00000000e+02 5.84950029e-02 2.95904370e-02]]


In [73]:
distributions = "norm_norm_"

In [74]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(483, 490))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):
         
        t_1 = [stats.norm, 0, (10 ** v)]

        t_2 = [stats.norm, 0, 1.112 * (10 ** v)]

        t_3 = [stats.norm, 0, 1.224 * (10 ** v)]

        t_4 = [stats.norm, 0, 1.336 * (10 ** v)]

        paramlist = [
            [stats.norm, 0, (10 ** v)],
            [stats.norm, 0, 0],
            (
                [t_1] * hierarchy[2]
                + [t_2] * hierarchy[2]
                + [t_3] * hierarchy[2]
                + [t_4] * hierarchy[2]
            )
            * hierarchy[0],
            [stats.norm, 0, 1],
        ]

        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()


[0.01       0.04928473 0.0494807 ]
[0.1        0.04791299 0.04546345]
[0.31622777 0.04810896 0.03742896]
[1.         0.04742308 0.02674897]
[3.16227766 0.05075446 0.02400549]
[10.          0.05006859  0.02351558]
[1.00000000e+02 5.12443661e-02 2.42014501e-02]
Wall time: 17min 33s


In [75]:
print(final)


[[1.00000000e-02 4.92847345e-02 4.94806976e-02]
 [1.00000000e-01 4.79129924e-02 4.54634529e-02]
 [3.16227766e-01 4.81089555e-02 3.74289634e-02]
 [1.00000000e+00 4.74230845e-02 2.67489712e-02]
 [3.16227766e+00 5.07544582e-02 2.40054870e-02]
 [1.00000000e+01 5.00685871e-02 2.35155791e-02]
 [1.00000000e+02 5.12443661e-02 2.42014501e-02]]


In [76]:
distributions = "pareto_pareto_"

In [77]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(490, 497))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):


        t_1 = [stats.pareto, 2.839, 0, (10 ** v)]

        loc_correction_2 = stats.pareto.mean(2.839, 0, (10 ** v)) - stats.pareto.mean(
            2.839, 0, 1.112 * (10 ** v)
        )

        t_2 = [stats.pareto, 2.839, loc_correction_2, 1.112 * (10 ** v)]

        loc_correction_3 = stats.pareto.mean(2.839, 0, (10 ** v)) - stats.pareto.mean(
            2.839, 0, 1.224 * (10 ** v)
        )

        t_3 = [stats.pareto, 2.839, loc_correction_3, 1.224 * (10 ** v)]

        loc_correction_4 = stats.pareto.mean(2.839, 0, (10 ** v)) - stats.pareto.mean(
            2.839, 0, 1.336 * (10 ** v)
        )

        t_4 = [stats.pareto, 2.839, loc_correction_4, 1.336 * (10 ** v)]

        paramlist = [
            [stats.pareto, 2.839, 0, (10 ** v)],
            [stats.norm, 0, 0],
            (
                [t_1] * hierarchy[2]
                + [t_2] * hierarchy[2]
                + [t_3] * hierarchy[2]
                + [t_4] * hierarchy[2]
            )
            * hierarchy[0],
            [stats.pareto, 2.839],
        ]

        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])

    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()



[0.01       0.05388987 0.0436018 ]
[0.1        0.05535959 0.04252401]
[0.31622777 0.04987262 0.03625318]
[1.         0.05349794 0.03370566]
[3.16227766 0.05467372 0.03017833]
[10.          0.058495    0.02763081]
[1.00000000e+02 5.94748187e-02 2.69449344e-02]
Wall time: 17min 41s


In [78]:
print(final)

[[1.00000000e-02 5.38898687e-02 4.36018029e-02]
 [1.00000000e-01 5.53595924e-02 4.25240055e-02]
 [3.16227766e-01 4.98726239e-02 3.62531844e-02]
 [1.00000000e+00 5.34979424e-02 3.37056633e-02]
 [3.16227766e+00 5.46737213e-02 3.01783265e-02]
 [1.00000000e+01 5.84950029e-02 2.76308054e-02]
 [1.00000000e+02 5.94748187e-02 2.69449344e-02]]


In [79]:
distributions = "gamma_gamma_"

In [80]:
%%time

loop_count = 729


interclass_corr = [-2, -1, -0.5, 0, 0.5, 1, 2]
seed = tuple(i for i in range(496, 503))
final = np.empty((len(interclass_corr), 3))

  

if __name__ ==  '__main__': 
    num_processors = 14

    containers = [hierarchy] * num_processors

    p=Pool(processes = num_processors)

    for idx, v in enumerate(interclass_corr):
        
        t_1 = [stats.gamma, 2, 0, (10 ** v)]

        loc_correction_2 = stats.gamma.mean(2, 0, (10 ** v)) - stats.gamma.mean(
            2, 0, 1.112 * (10 ** v)
        )

        t_2 = [stats.gamma, 2, loc_correction_2, 1.112 * (10 ** v)]

        loc_correction_3 = stats.gamma.mean(2, 0, (10 ** v)) - stats.gamma.mean(
            2, 0, 1.224 * (10 ** v)
        )

        t_3 = [stats.gamma, 2, loc_correction_3, 1.224 * (10 ** v)]

        loc_correction_4 = stats.gamma.mean(2, 0, (10 ** v)) - stats.gamma.mean(
            2, 0, 1.336 * (10 ** v)
        )

        t_4 = [stats.gamma, 2, loc_correction_4, 1.336 * (10 ** v)]

        paramlist = [
            [stats.gamma, 2, 0, (10 ** v)],
            [stats.norm, 0, 0],
            (
                [t_1] * hierarchy[2]
                + [t_2] * hierarchy[2]
                + [t_3] * hierarchy[2]
                + [t_4] * hierarchy[2]
            )
            * hierarchy[0],
            [stats.gamma, 2],
        ]

        paramlist = [paramlist] * num_processors

        ss = np.random.SeedSequence(seedlist[seed[idx]])
        child_seeds = ss.spawn(num_processors)
        seeds = [np.random.default_rng(s) for s in child_seeds]

        output = p.starmap(worker, zip(containers, paramlist, seeds))

        final[idx, 0] = 10**v     
        final[idx, 1:] = (np.asarray(output) <= 0.05).sum(axis=2).sum(axis=0) / (loop_count*num_processors)
        print(final[idx])


    containerstr = str(hierarchy).translate({ord(','):ord('_'), ord('['):None, ord(']'):None, ord(' '):None})
    filename = containerstr + "data_" + distributions + ".csv"
    np.savetxt(os.path.join(folder, filename), final, delimiter=',') 

    p.close()



[0.01       0.05095042 0.04801097]
[0.1        0.05291005 0.04869684]
[0.31622777 0.04850088 0.03938859]
[1.         0.04320988 0.02635704]
[3.16227766 0.05379189 0.02684695]
[10.          0.05075446  0.02508328]
[1.00000000e+02 5.06564766e-02 2.43974133e-02]
Wall time: 17min 45s


In [81]:
print(final)


[[1.00000000e-02 5.09504213e-02 4.80109739e-02]
 [1.00000000e-01 5.29100529e-02 4.86968450e-02]
 [3.16227766e-01 4.85008818e-02 3.93885949e-02]
 [1.00000000e+00 4.32098765e-02 2.63570449e-02]
 [3.16227766e+00 5.37918871e-02 2.68469528e-02]
 [1.00000000e+01 5.07544582e-02 2.50832843e-02]
 [1.00000000e+02 5.06564766e-02 2.43974133e-02]]
